title: Settings
data:
  site_name: 'TSK Portfolio 2025'
  social:
    -
      id: YStG1Qdo
      name: Github
      url: 'https://github.com/statamic/starter-kit-cool-writings'
      icon: site/social-icons/github.svg
    -
      id: s6wjiJJi
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
  profile_image: site/profile-image.png
