title: 'Global Settings'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              character_limit: 0
              type: text
              display: 'Site Name'
          -
            handle: social
            field:
              add_row: 'Add Link'
              type: grid
              instructions: 'Set any social media links'
              display: Social
              fields:
                -
                  handle: name
                  field:
                    type: text
                    localizable: false
                    display: Name
                -
                  handle: url
                  field:
                    character_limit: 0
                    type: text
                    localizable: false
                    display: URL
                -
                  handle: icon
                  field:
                    container: assets
                    mode: list
                    restrict: true
                    folder: site/social-icons
                    allow_uploads: true
                    max_files: 1
                    type: assets
                    localizable: false
                    display: Icon
          -
            handle: profile_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Profile Image'
              sortable: false
              mode: grid
