tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              localizable: true
          -
            handle: project_link
            field:
              type: link
              display: 'Project Link'
          -
            handle: image
            field:
              max_files: 1
              container: assets
              type: assets
              display: Image
          -
            handle: link_text
            field:
              type: text
              display: 'Link Text'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
title: Project
